# Generated by Django 3.1.1 on 2020-09-24 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swapp', '0004_auto_20200924_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='usernew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usernew', to='swapp.usernew'),
        ),
        migrations.AddField(
            model_name='reply',
            name='from_usernew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_usernew', to='swapp.usernew'),
        ),
        migrations.AddField(
            model_name='reply',
            name='to_usernew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_usernew', to='swapp.usernew'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
