# Generated by Django 3.1.1 on 2020-09-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0005_auto_20200924_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='coins',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
