# Generated by Django 3.1.1 on 2020-09-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0006_ask_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='coins',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
