# Generated by Django 3.1.1 on 2020-09-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0007_auto_20200924_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
