# Generated by Django 3.1.1 on 2020-09-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0012_auto_20200930_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='contacted',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='help',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='usernew',
        ),
        migrations.AddField(
            model_name='chat',
            name='text',
            field=models.TextField(default='q'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='q', max_length=500),
            preserve_default=False,
        ),
    ]
