# Generated by Django 3.1.1 on 2020-09-30 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0014_auto_20200930_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='help',
            name='to_usernew',
        ),
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Contacted',
        ),
        migrations.DeleteModel(
            name='Help',
        ),
    ]
