# Generated by Django 3.1.1 on 2020-10-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0015_auto_20200930_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='classe',
        ),
        migrations.AddField(
            model_name='chat',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
