# Generated by Django 3.1.1 on 2020-10-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0016_auto_20201001_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='bad',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
