# Generated by Django 3.1.1 on 2020-10-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0019_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='yn',
            field=models.BooleanField(default=False),
        ),
    ]
