# Generated by Django 3.1.1 on 2020-10-01 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0021_yes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yes',
            name='bad',
        ),
        migrations.AddField(
            model_name='yes',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swapp.reply'),
        ),
    ]
