# Generated by Django 3.1.1 on 2020-10-01 11:24

from django.db import migrations, models
import swapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0023_yes_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yes',
            name='evaluation',
            field=models.IntegerField(default=5, validators=[swapp.models.val]),
            preserve_default=False,
        ),
    ]
