# Generated by Django 3.1.1 on 2020-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0024_auto_20201001_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yes',
            name='evaluation',
            field=models.IntegerField(),
        ),
    ]
