# Generated by Django 3.1.1 on 2020-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0025_auto_20201001_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='coins_ask',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solved',
            name='coins_reply',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
